---
- name: First
  hosts: all_servers
  remote_user: osboxes
  vars_prompt:
      - name: machine
        prompt: Enter IP addr certain machine
        private: false
      - name: source
        prompt: Enter altarnative path 1 to certain machine
        private: false

  vars:
    path: /home/osboxes/test_ansible
    output: /home/osboxes/project/
    file: text1.txt

  tasks:
    - name: "copyfile"
      fetch:
        src: '{{ path }}/{{ file }}'
        dest: '{{ output }}'

    - name: "copyfile for certain machine"
      fetch:
        src: '{{ source }}/{{ file }}'
        dest: '{{ output }}'
      when: ansible_host== '{{ machine }}'
      
    - name: "excel"
      ansible.builtin.script:
        cmd: /bin/python3 excel.py "{{ file }}"
      when: ansible_host == "target3"
      
  
